# Generated by Django 5.0.2 on 2024-02-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, unique=True)),
                ("description", models.TextField(blank=True)),
                ("pet_project_ideas", models.TextField(blank=True)),
                ("useful_links", models.TextField(blank=True)),
                ("useful_books", models.TextField(blank=True)),
                ("useful_courses", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, unique=True)),
                ("description", models.TextField(blank=True)),
                ("skills", models.ManyToManyField(blank=True, to="vita_test.skill")),
            ],
        ),
        migrations.AddField(
            model_name="skill",
            name="topics",
            field=models.ManyToManyField(blank=True, to="vita_test.topic"),
        ),
    ]
