version: '3.9'

services:

  db:
    image: postgres:16.2-bullseye
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: app_user
      POSTGRES_DB: test_task

    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app/
    entrypoint: "./manage.py runserver 0.0.0.0:8000"



volumes:
  pg_data: